image: debian:stable-slim
before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt -qq update
  - apt-get -qq install apt-utils
  # Note: openssh-client contains ssh-agent, that it is required by Docker.
  - apt-get -qq install --no-install-recommends ca-certificates cython gcc git python python-dev python-numpy python-pip python-tables python-yaml

test_til_france:
  only:
    - gitlab-runner
  script:
    # Install til-core
    - pwd
    - git clone https://github.com/TaxIPP-Life/til-core.git ../til-core
    - pip install -e ../til-core/.
    # Install liam2
    - git clone https://github.com/benjello/liam2.git ../liam2
    - git --git-dir=../liam2/.git --work-tree=../liam2 checkout global_parameter
    - pip install -e ../liam2/.
    - cd ../liam2
    - python setup.py build_ext --inplace
    # Install til-france
    - cd ../til-france
    - pip install -e .
    - cd /home/ipp
    - ls . | cat

  stage: build