image: debian:stable-slim
before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt -qq update
  - apt-get -qq install apt-utils
  # Note: openssh-client contains ssh-agent, that it is required by Docker.
  - apt-get -qq install --no-install-recommends ca-certificates python python-pip git python-numpy

test_til_france:
  only:
    - gitlab-runner
  script:
    # Install til-core
    - git clone https://github.com/benjello/Til.git ../til-core
    - pip install -e ../til-core/.
    # Install til-france
    - pip install -e .
    - cd /home/ipp
    - ls . | cat

  stage: build