env:
  - USE_TRAVIS=true
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq cython python-matplotlib python-numexpr python-numpy python-pandas python-yaml python-sip
#   - sudo apt-get build-dep python-tables
# install:
#   - pip install flake8  # Not yet available in Debian stable
#   - pip install tables  # For version > 3
#   - pip install -e .
#   - python setup.py build_ext --inplace
sudo: false # Use new Travis container-based infrastructure
language: python
python: 2.7
cache: pip
install:
  - pip install --upgrade pip wheel  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install flake8
  # - pip install pandas nose numexpr numpy pytables cython
  - pip install --editable .[test] -r requirements.txt
  - python setup.py build_ext --inplace
script: make test-ci
