env:
  - USE_TRAVIS=true
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq cython python-matplotlib python-numexpr python-numpy python-pandas python-yaml python-sip
#   - sudo apt-get build-dep python-tables
# install:
#   - pip install flake8  # Not yet available in Debian stable
#   - pip install tables  # For version > 3
#   - pip install -e .
#   - python setup.py build_ext --inplace
sudo: false # Use new Travis container-based infrastructure
language: python
python: 2.7
cache: pip
install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip pandas nose numexpr numpy pytables cython
  - source activate test-environment
  - pip install flake8  # Not yet available in Ubuntu precise (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)
  - pip install --editable .[test] -r requirements.txt
  - python setup.py build_ext --inplace
script: make test-ci
